spring:
  rabbitmq:
    addresses: 192.168.3.3:5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        # 开启手动ack，消息消息的时候，就必须发送ack确认，不然消息永远还在队列中
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
      # 自定义配置
      order:
        queue:
          name: queue-2
          durable: true
        exchange:
          name: exchange-2
          durable: true
          type: topic
          ignoreDeclarationExceptions: true
        key: springboot.rabbitmq.*